# Generated by Django 5.1.15 on 2026-05-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('recipient', models.EmailField(db_index=True, max_length=254, verbose_name='recipient')),
                ('subject', models.CharField(max_length=300, verbose_name='subject')),
                ('template', models.CharField(blank=True, default='', help_text="Template name yoki bo'sh (raw message)", max_length=80, verbose_name='template')),
                ('body', models.TextField(blank=True, default='', verbose_name='body')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_f70bc1_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_d84ea4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Order created'), ('order_confirmed', 'Order confirmed'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('order_cancelled', 'Order cancelled'), ('payment_paid', 'Payment confirmed'), ('review_approved', 'Review approved'), ('system', 'System message')], db_index=True, max_length=40, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(blank=True, default=dict, help_text="Tegishli ma'lumotlar (order_number, link, image_url, ...)", verbose_name='payload')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx')],
            },
        ),
    ]
