# Generated by Django 5.1.15 on 2026-05-30 05:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='logo')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0.00 dan 100.00 gacha', max_digits=5, verbose_name='commission rate (%)')),
                ('owner', models.ForeignKey(blank=True, help_text='Multi-vendor rejimida vendor egasi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
                'ordering': ('name',),
            },
        ),
    ]
