"""
~500 ta noyob mahsulot — Uzum.uz va shunga o'xshash marketplace'larda
uchraydigan real brand+model nomlar bilan.

Format: PRODUCT_SEEDS[leaf_category_slug] = [
    (name_uz, name_ru, name_en, base_price_uzs, img_keyword),
    ...
]

`img_keyword` — loremflickr/picsum uchun mavzu so'zi (`iphone`, `sneakers`).
"""

from __future__ import annotations


PRODUCT_SEEDS: dict[str, list[tuple[str, str, str, int, str]]] = {
    # ========================================================================
    # ELEKTRONIKA — Smartfonlar (~50)
    # ========================================================================
    "smartfonlar": [
        ("iPhone 15 Pro Max 256GB", "iPhone 15 Pro Max 256ГБ", "iPhone 15 Pro Max 256GB", 18_900_000, "iphone"),
        ("iPhone 15 Pro 128GB", "iPhone 15 Pro 128ГБ", "iPhone 15 Pro 128GB", 15_400_000, "iphone"),
        ("iPhone 15 Plus", "iPhone 15 Plus", "iPhone 15 Plus", 13_200_000, "iphone"),
        ("iPhone 15 128GB", "iPhone 15 128ГБ", "iPhone 15 128GB", 11_900_000, "iphone"),
        ("iPhone 14 Pro Max", "iPhone 14 Pro Max", "iPhone 14 Pro Max", 16_200_000, "iphone"),
        ("iPhone 14 Pro 256GB", "iPhone 14 Pro 256ГБ", "iPhone 14 Pro 256GB", 13_500_000, "iphone"),
        ("iPhone 14 128GB", "iPhone 14 128ГБ", "iPhone 14 128GB", 11_200_000, "iphone"),
        ("iPhone 13 128GB", "iPhone 13 128ГБ", "iPhone 13 128GB", 8_900_000, "iphone"),
        ("iPhone 13 mini", "iPhone 13 mini", "iPhone 13 mini", 8_400_000, "iphone"),
        ("iPhone 12 64GB", "iPhone 12 64ГБ", "iPhone 12 64GB", 7_200_000, "iphone"),
        ("iPhone 11 64GB", "iPhone 11 64ГБ", "iPhone 11 64GB", 5_900_000, "iphone"),
        ("iPhone SE 2022", "iPhone SE 2022", "iPhone SE 2022", 4_800_000, "iphone"),
        ("Samsung Galaxy S24 Ultra", "Samsung Galaxy S24 Ultra", "Samsung Galaxy S24 Ultra", 16_500_000, "samsung-phone"),
        ("Samsung Galaxy S24 Plus", "Samsung Galaxy S24+", "Samsung Galaxy S24+", 13_400_000, "samsung-phone"),
        ("Samsung Galaxy S24", "Samsung Galaxy S24", "Samsung Galaxy S24", 11_200_000, "samsung-phone"),
        ("Samsung Galaxy S23 FE", "Samsung Galaxy S23 FE", "Samsung Galaxy S23 FE", 7_400_000, "samsung-phone"),
        ("Samsung Galaxy A55", "Samsung Galaxy A55", "Samsung Galaxy A55", 5_400_000, "phone"),
        ("Samsung Galaxy A35", "Samsung Galaxy A35", "Samsung Galaxy A35", 4_200_000, "phone"),
        ("Samsung Galaxy A25", "Samsung Galaxy A25", "Samsung Galaxy A25", 3_200_000, "phone"),
        ("Samsung Galaxy A15", "Samsung Galaxy A15", "Samsung Galaxy A15", 2_500_000, "phone"),
        ("Samsung Galaxy Z Flip 5", "Samsung Galaxy Z Flip 5", "Samsung Galaxy Z Flip 5", 14_200_000, "foldable-phone"),
        ("Samsung Galaxy Z Fold 5", "Samsung Galaxy Z Fold 5", "Samsung Galaxy Z Fold 5", 22_500_000, "foldable-phone"),
        ("Xiaomi 14 Ultra", "Xiaomi 14 Ultra", "Xiaomi 14 Ultra", 13_900_000, "xiaomi-phone"),
        ("Xiaomi 14T Pro", "Xiaomi 14T Pro", "Xiaomi 14T Pro", 8_700_000, "xiaomi-phone"),
        ("Xiaomi 14T", "Xiaomi 14T", "Xiaomi 14T", 7_900_000, "smartphone"),
        ("Xiaomi Redmi Note 13 Pro Plus", "Xiaomi Redmi Note 13 Pro+", "Xiaomi Redmi Note 13 Pro+", 4_500_000, "xiaomi-phone"),
        ("Xiaomi Redmi Note 13", "Xiaomi Redmi Note 13", "Xiaomi Redmi Note 13", 3_200_000, "xiaomi-phone"),
        ("Xiaomi Redmi 13C", "Xiaomi Redmi 13C", "Xiaomi Redmi 13C", 1_800_000, "phone"),
        ("OnePlus 12 256GB", "OnePlus 12 256ГБ", "OnePlus 12 256GB", 9_500_000, "smartphone"),
        ("OnePlus Nord 4", "OnePlus Nord 4", "OnePlus Nord 4", 5_400_000, "smartphone"),
        ("Honor Magic 6 Pro", "Honor Magic 6 Pro", "Honor Magic 6 Pro", 10_200_000, "smartphone"),
        ("Honor 200 Pro", "Honor 200 Pro", "Honor 200 Pro", 6_900_000, "smartphone"),
        ("Realme GT 5 Pro", "Realme GT 5 Pro", "Realme GT 5 Pro", 7_800_000, "smartphone"),
        ("Realme C67", "Realme C67", "Realme C67", 2_400_000, "phone"),
        ("Google Pixel 8 Pro", "Google Pixel 8 Pro", "Google Pixel 8 Pro", 12_500_000, "smartphone"),
        ("Google Pixel 8", "Google Pixel 8", "Google Pixel 8", 9_400_000, "smartphone"),
        ("Huawei Pura 70", "Huawei Pura 70", "Huawei Pura 70", 11_900_000, "smartphone"),
        ("Huawei Nova 12", "Huawei Nova 12", "Huawei Nova 12", 5_200_000, "phone"),
        ("OPPO Reno 11 Pro", "OPPO Reno 11 Pro", "OPPO Reno 11 Pro", 6_400_000, "smartphone"),
        ("OPPO A98", "OPPO A98", "OPPO A98", 3_200_000, "phone"),
        ("Vivo V30", "Vivo V30", "Vivo V30", 5_200_000, "smartphone"),
        ("Tecno Camon 30", "Tecno Camon 30", "Tecno Camon 30", 3_400_000, "phone"),
        ("Infinix Note 30", "Infinix Note 30", "Infinix Note 30", 2_900_000, "phone"),
        ("Apple Watch Series 9 45mm", "Apple Watch Series 9 45мм", "Apple Watch Series 9 45mm", 5_200_000, "smartwatch"),
        ("Apple Watch SE 2", "Apple Watch SE 2", "Apple Watch SE 2", 3_400_000, "smartwatch"),
        ("Samsung Galaxy Watch 6", "Samsung Galaxy Watch 6", "Samsung Galaxy Watch 6", 3_900_000, "smartwatch"),
        ("Xiaomi Mi Band 8", "Xiaomi Mi Band 8", "Xiaomi Mi Band 8", 480_000, "fitness-band"),
        ("Power Bank 20000mAh Anker", "Power Bank 20000мАч Anker", "Anker Power Bank 20000mAh", 380_000, "power-bank"),
        ("Power Bank 10000mAh", "Power Bank 10000мАч", "Power Bank 10000mAh", 180_000, "power-bank"),
        ("USB-C zaryadlovchi 65W", "Зарядка USB-C 65Вт", "USB-C 65W charger", 240_000, "charger"),
        ("Telefon g'ilofi silikon", "Силиконовый чехол", "Silicone phone case", 65_000, "phone-case"),
    ],

    # ========================================================================
    # ELEKTRONIKA — Noutbuklar (~30)
    # ========================================================================
    "noutbuklar": [
        ("MacBook Pro 16 M3 Max", "MacBook Pro 16 M3 Max", "MacBook Pro 16 M3 Max", 38_500_000, "macbook"),
        ("MacBook Pro 14 M3 Pro", "MacBook Pro 14 M3 Pro", "MacBook Pro 14 M3 Pro", 28_400_000, "macbook"),
        ("MacBook Pro 14 M3", "MacBook Pro 14 M3", "MacBook Pro 14 M3", 22_900_000, "macbook"),
        ("MacBook Air 15 M3", "MacBook Air 15 M3", "MacBook Air 15 M3", 19_800_000, "macbook"),
        ("MacBook Air 13 M3", "MacBook Air 13 M3", "MacBook Air 13 M3", 18_500_000, "macbook"),
        ("MacBook Air 13 M2", "MacBook Air 13 M2", "MacBook Air 13 M2", 14_200_000, "macbook"),
        ("Dell XPS 15 OLED", "Dell XPS 15 OLED", "Dell XPS 15 OLED", 19_400_000, "laptop-dell"),
        ("Dell XPS 13 Plus", "Dell XPS 13 Plus", "Dell XPS 13 Plus", 14_200_000, "laptop-dell"),
        ("Dell Inspiron 15", "Dell Inspiron 15", "Dell Inspiron 15", 7_800_000, "laptop"),
        ("Dell Latitude 5440", "Dell Latitude 5440", "Dell Latitude 5440", 12_500_000, "business-laptop"),
        ("HP Spectre x360 14", "HP Spectre x360 14", "HP Spectre x360 14", 17_800_000, "ultrabook"),
        ("HP EliteBook 840 G10", "HP EliteBook 840 G10", "HP EliteBook 840 G10", 13_500_000, "business-laptop"),
        ("HP Pavilion 15", "HP Pavilion 15", "HP Pavilion 15", 7_800_000, "laptop-hp"),
        ("HP Omen 16 Gaming", "HP Omen 16 Gaming", "HP Omen 16 Gaming", 18_900_000, "gaming-laptop"),
        ("Lenovo ThinkPad X1 Carbon Gen 12", "Lenovo ThinkPad X1 Carbon Gen 12", "Lenovo ThinkPad X1 Carbon Gen 12", 21_400_000, "business-laptop"),
        ("Lenovo ThinkPad T14", "Lenovo ThinkPad T14", "Lenovo ThinkPad T14", 14_800_000, "business-laptop"),
        ("Lenovo IdeaPad 5 Pro", "Lenovo IdeaPad 5 Pro", "Lenovo IdeaPad 5 Pro", 9_500_000, "laptop"),
        ("Lenovo Legion 5 Pro", "Lenovo Legion 5 Pro", "Lenovo Legion 5 Pro", 15_800_000, "gaming-laptop"),
        ("Lenovo Yoga 9i", "Lenovo Yoga 9i", "Lenovo Yoga 9i", 17_200_000, "ultrabook"),
        ("Asus ROG Zephyrus G14", "Asus ROG Zephyrus G14", "Asus ROG Zephyrus G14", 19_500_000, "gaming-laptop"),
        ("Asus TUF Gaming F15", "Asus TUF Gaming F15", "Asus TUF Gaming F15", 12_400_000, "gaming-laptop"),
        ("Asus ZenBook 14 OLED", "Asus ZenBook 14 OLED", "Asus ZenBook 14 OLED", 13_900_000, "ultrabook"),
        ("Asus VivoBook 15", "Asus VivoBook 15", "Asus VivoBook 15", 6_800_000, "laptop"),
        ("Acer Swift 5", "Acer Swift 5", "Acer Swift 5", 11_200_000, "ultrabook"),
        ("Acer Predator Helios 16", "Acer Predator Helios 16", "Acer Predator Helios 16", 17_800_000, "gaming-laptop"),
        ("Acer Aspire 5", "Acer Aspire 5", "Acer Aspire 5", 6_400_000, "laptop"),
        ("Microsoft Surface Laptop 6", "Microsoft Surface Laptop 6", "Microsoft Surface Laptop 6", 18_400_000, "ultrabook"),
        ("Microsoft Surface Pro 9", "Microsoft Surface Pro 9", "Microsoft Surface Pro 9", 14_500_000, "tablet-laptop"),
        ("Huawei MateBook X Pro", "Huawei MateBook X Pro", "Huawei MateBook X Pro", 15_900_000, "ultrabook"),
        ("Apple iPad Pro 13 M4", "Apple iPad Pro 13 M4", "Apple iPad Pro 13 M4", 18_900_000, "ipad"),
        ("Apple iPad Air 11 M2", "Apple iPad Air 11 M2", "Apple iPad Air 11 M2", 11_400_000, "ipad"),
        ("Samsung Galaxy Tab S9 Ultra", "Samsung Galaxy Tab S9 Ultra", "Samsung Galaxy Tab S9 Ultra", 14_500_000, "tablet"),
    ],

    # ========================================================================
    # ELEKTRONIKA — Audio (~30)
    # ========================================================================
    "audio": [
        ("Apple AirPods Pro 2", "Apple AirPods Pro 2", "Apple AirPods Pro 2", 3_100_000, "earbuds"),
        ("Apple AirPods 3", "Apple AirPods 3", "Apple AirPods 3", 2_200_000, "earbuds"),
        ("Apple AirPods Max", "Apple AirPods Max", "Apple AirPods Max", 6_800_000, "headphones"),
        ("Sony WH-1000XM5", "Sony WH-1000XM5", "Sony WH-1000XM5", 4_200_000, "headphones"),
        ("Sony WH-1000XM4", "Sony WH-1000XM4", "Sony WH-1000XM4", 3_400_000, "headphones"),
        ("Sony WF-1000XM5", "Sony WF-1000XM5", "Sony WF-1000XM5", 3_200_000, "earbuds-sony"),
        ("Sony WF-1000XM4", "Sony WF-1000XM4", "Sony WF-1000XM4", 2_400_000, "earbuds-sony"),
        ("Bose QuietComfort Ultra", "Bose QuietComfort Ultra", "Bose QuietComfort Ultra", 5_400_000, "headphones-bose"),
        ("Bose QuietComfort 45", "Bose QuietComfort 45", "Bose QuietComfort 45", 4_500_000, "headphones-bose"),
        ("Samsung Galaxy Buds Pro 3", "Samsung Galaxy Buds Pro 3", "Samsung Galaxy Buds Pro 3", 2_900_000, "earbuds"),
        ("Samsung Galaxy Buds FE", "Samsung Galaxy Buds FE", "Samsung Galaxy Buds FE", 1_200_000, "earbuds"),
        ("JBL Tour Pro 2", "JBL Tour Pro 2", "JBL Tour Pro 2", 2_400_000, "earbuds"),
        ("JBL Tune 770NC", "JBL Tune 770NC", "JBL Tune 770NC", 1_500_000, "headphones"),
        ("JBL Flip 6 Speaker", "JBL Flip 6 колонка", "JBL Flip 6 speaker", 1_400_000, "speaker"),
        ("JBL Charge 5", "JBL Charge 5", "JBL Charge 5", 2_100_000, "speaker"),
        ("JBL Xtreme 3", "JBL Xtreme 3", "JBL Xtreme 3", 4_200_000, "speaker"),
        ("JBL Boombox 3", "JBL Boombox 3", "JBL Boombox 3", 6_800_000, "speaker"),
        ("Marshall Acton III", "Marshall Acton III", "Marshall Acton III", 3_400_000, "speaker-marshall"),
        ("Marshall Stanmore III", "Marshall Stanmore III", "Marshall Stanmore III", 5_200_000, "speaker-marshall"),
        ("Marshall Major IV", "Marshall Major IV", "Marshall Major IV", 1_900_000, "headphones"),
        ("Xiaomi Buds 4 Pro", "Xiaomi Buds 4 Pro", "Xiaomi Buds 4 Pro", 1_400_000, "earbuds"),
        ("Xiaomi Redmi Buds 5", "Xiaomi Redmi Buds 5", "Xiaomi Redmi Buds 5", 480_000, "earbuds"),
        ("Sennheiser Momentum 4", "Sennheiser Momentum 4", "Sennheiser Momentum 4", 4_800_000, "headphones"),
        ("Anker Soundcore Liberty 4", "Anker Soundcore Liberty 4", "Anker Soundcore Liberty 4", 1_400_000, "earbuds"),
        ("Anker Soundcore Motion+ Speaker", "Колонка Anker Soundcore Motion+", "Anker Soundcore Motion+ speaker", 1_200_000, "speaker"),
        ("Yamaha YH-E700A", "Yamaha YH-E700A", "Yamaha YH-E700A", 4_400_000, "headphones"),
        ("Beats Studio Pro", "Beats Studio Pro", "Beats Studio Pro", 4_900_000, "headphones"),
        ("Beats Fit Pro", "Beats Fit Pro", "Beats Fit Pro", 2_400_000, "earbuds"),
        ("Mikrofon Blue Yeti", "Микрофон Blue Yeti", "Blue Yeti microphone", 2_100_000, "microphone"),
        ("Microsoft Surface Headphones 2", "Microsoft Surface Headphones 2", "Microsoft Surface Headphones 2", 3_400_000, "headphones"),
    ],

    # ========================================================================
    # ELEKTRONIKA — Televizorlar (~20)
    # ========================================================================
    "televizorlar": [
        ("Samsung 65\" QLED 4K Q70C", "Samsung 65\" QLED 4K Q70C", "Samsung 65\" QLED 4K Q70C", 13_900_000, "tv"),
        ("Samsung 55\" QLED 4K Q60C", "Samsung 55\" QLED 4K Q60C", "Samsung 55\" QLED 4K Q60C", 9_500_000, "tv"),
        ("Samsung 50\" Crystal UHD", "Samsung 50\" Crystal UHD", "Samsung 50\" Crystal UHD", 6_400_000, "smart-tv"),
        ("Samsung 43\" Smart TV", "Samsung 43\" Smart TV", "Samsung 43\" Smart TV", 4_200_000, "smart-tv"),
        ("Samsung Neo QLED 75\"", "Samsung Neo QLED 75\"", "Samsung Neo QLED 75\"", 22_500_000, "big-tv"),
        ("LG OLED evo C3 65\"", "LG OLED evo C3 65\"", "LG OLED evo C3 65\"", 18_900_000, "oled-tv"),
        ("LG OLED 55\" B3", "LG OLED 55\" B3", "LG OLED 55\" B3", 12_400_000, "oled-tv"),
        ("LG NanoCell 75\"", "LG NanoCell 75\"", "LG NanoCell 75\"", 18_500_000, "big-tv"),
        ("LG UHD 50\"", "LG UHD 50\"", "LG UHD 50\"", 6_900_000, "smart-tv"),
        ("Sony Bravia XR A95L 65\"", "Sony Bravia XR A95L 65\"", "Sony Bravia XR A95L 65\"", 24_500_000, "tv"),
        ("Sony Bravia X90L 55\"", "Sony Bravia X90L 55\"", "Sony Bravia X90L 55\"", 10_500_000, "sony-tv"),
        ("Sony Bravia 50\" X80L", "Sony Bravia 50\" X80L", "Sony Bravia 50\" X80L", 7_200_000, "sony-tv"),
        ("Hisense 65\" U7K Mini-LED", "Hisense 65\" U7K Mini-LED", "Hisense 65\" U7K Mini-LED", 9_800_000, "tv"),
        ("Hisense 55\" A6K", "Hisense 55\" A6K", "Hisense 55\" A6K", 4_900_000, "smart-tv"),
        ("TCL 55\" QLED C645", "TCL 55\" QLED C645", "TCL 55\" QLED C645", 5_800_000, "tv"),
        ("TCL 43\" Smart TV", "TCL 43\" Smart TV", "TCL 43\" Smart TV", 3_400_000, "smart-tv"),
        ("Artel 55\" UHD Smart", "Artel 55\" UHD Smart", "Artel 55\" UHD Smart", 5_400_000, "smart-tv"),
        ("Artel 43\" Smart TV", "Artel 43\" Smart TV", "Artel 43\" Smart TV", 3_400_000, "smart-tv"),
        ("Artel 32\" HD", "Artel 32\" HD", "Artel 32\" HD", 2_100_000, "tv"),
        ("Apple TV 4K (2022)", "Apple TV 4K (2022)", "Apple TV 4K (2022)", 1_900_000, "tv-box"),
    ],

    # ========================================================================
    # KIYIM-KECHAK — Erkaklar (~35)
    # ========================================================================
    "erkaklar": [
        ("Nike Air Max 270", "Nike Air Max 270", "Nike Air Max 270", 1_800_000, "sneakers"),
        ("Nike Air Force 1 White", "Nike Air Force 1 White", "Nike Air Force 1 White", 1_650_000, "sneakers"),
        ("Nike Air Jordan 1 Mid", "Nike Air Jordan 1 Mid", "Nike Air Jordan 1 Mid", 2_400_000, "sneakers"),
        ("Nike Dunk Low Retro", "Nike Dunk Low Retro", "Nike Dunk Low Retro", 1_900_000, "sneakers"),
        ("Nike Pegasus 40", "Nike Pegasus 40", "Nike Pegasus 40", 1_550_000, "running-shoes"),
        ("Adidas Ultraboost 22", "Adidas Ultraboost 22", "Adidas Ultraboost 22", 2_100_000, "running-shoes"),
        ("Adidas Samba OG", "Adidas Samba OG", "Adidas Samba OG", 1_400_000, "sneakers"),
        ("Adidas Gazelle Indoor", "Adidas Gazelle Indoor", "Adidas Gazelle Indoor", 1_350_000, "sneakers"),
        ("Adidas Stan Smith", "Adidas Stan Smith", "Adidas Stan Smith", 980_000, "sneakers"),
        ("Puma RS-X", "Puma RS-X", "Puma RS-X", 1_250_000, "sneakers"),
        ("New Balance 574", "New Balance 574", "New Balance 574", 1_400_000, "sneakers"),
        ("New Balance 990v6", "New Balance 990v6", "New Balance 990v6", 2_800_000, "sneakers"),
        ("Converse Chuck 70 High", "Converse Chuck 70 High", "Converse Chuck 70 High", 950_000, "sneakers"),
        ("Vans Old Skool", "Vans Old Skool", "Vans Old Skool", 850_000, "sneakers"),
        ("Erkaklar klassik tufli charm", "Мужские классические туфли", "Men's classic leather shoes", 1_200_000, "dress-shoes"),
        ("Loafers charm", "Лоферы кожаные", "Leather loafers", 980_000, "dress-shoes"),
        ("Yengil yozgi kedalar", "Лёгкие летние кеды", "Light summer kicks", 650_000, "shoes"),
        ("Qishki etiklar", "Зимние ботинки", "Winter boots", 1_400_000, "boots"),
        ("Sandallar", "Сандалии мужские", "Men's sandals", 420_000, "sandals"),
        ("Zara klassik ko'ylak oq", "Классическая белая рубашка Zara", "Zara classic white shirt", 450_000, "shirt"),
        ("H&M paxta polo futbolka", "Поло из хлопка H&M", "H&M cotton polo shirt", 320_000, "polo"),
        ("Erkaklar futbolkasi paxta", "Мужская хлопковая футболка", "Men's cotton T-shirt", 220_000, "tshirt-men"),
        ("Uniqlo HEATTECH futbolka", "Uniqlo HEATTECH футболка", "Uniqlo HEATTECH T-shirt", 280_000, "tshirt-men"),
        ("Erkaklar sviteri jundan", "Мужской шерстяной свитер", "Men's wool sweater", 740_000, "sweater"),
        ("Hoodie qora gradient", "Худи чёрное", "Black hoodie", 580_000, "hoodie"),
        ("Levi's 501 Jinsi", "Джинсы Levi's 501", "Levi's 501 jeans", 720_000, "jeans"),
        ("Levi's 511 Slim", "Levi's 511 Slim", "Levi's 511 Slim jeans", 680_000, "jeans"),
        ("Chinos shimlari bej", "Чинос бежевые", "Beige chinos", 540_000, "trousers"),
        ("Erkaklar qishki kurtkasi", "Мужская зимняя куртка", "Men's winter jacket", 890_000, "jacket"),
        ("North Face Puffer jacket", "North Face Puffer jacket", "North Face Puffer jacket", 2_400_000, "puffer-jacket"),
        ("Charm kurtka qora", "Чёрная кожаная куртка", "Black leather jacket", 1_650_000, "leather-jacket"),
        ("Klassik kostyum kuluvchi", "Классический мужской костюм", "Classic men's suit", 1_650_000, "suit"),
        ("Galstuk shoyi", "Шёлковый галстук", "Silk tie", 180_000, "tie"),
        ("Charm kamar", "Кожаный ремень", "Leather belt", 240_000, "belt"),
        ("Hamyon charm", "Кожаный кошелёк", "Leather wallet", 320_000, "wallet"),
    ],

    # ========================================================================
    # KIYIM-KECHAK — Ayollar (~35)
    # ========================================================================
    "ayollar": [
        ("Zara yozgi gulli libos", "Летнее платье в цветочек Zara", "Zara floral summer dress", 580_000, "dress"),
        ("Zara mini libos", "Мини-платье Zara", "Zara mini dress", 520_000, "dress"),
        ("Mango midi libos qora", "Mango чёрное миди-платье", "Mango black midi dress", 680_000, "dress"),
        ("H&M coctail libos", "Коктейльное платье H&M", "H&M cocktail dress", 480_000, "dress"),
        ("Shoyi bluzka oq", "Белая шёлковая блузка", "White silk blouse", 540_000, "blouse"),
        ("Ko'ylak-platye keng", "Платье-рубашка свободного кроя", "Loose shirt-dress", 480_000, "dress-shirt"),
        ("A-line yubka", "Юбка А-силуэта", "A-line skirt", 360_000, "skirt"),
        ("Pleated yubka midi", "Плиссированная юбка миди", "Pleated midi skirt", 420_000, "skirt"),
        ("Jinsi yubka", "Джинсовая юбка", "Denim skirt", 320_000, "skirt"),
        ("Ayollar futbolkasi", "Женская футболка", "Women's T-shirt", 180_000, "tshirt"),
        ("Crop top sariq", "Жёлтый кроп-топ", "Yellow crop top", 220_000, "crop-top"),
        ("Bluzka shifon", "Шифоновая блузка", "Chiffon blouse", 380_000, "blouse"),
        ("Tunika rang-barang", "Туника яркая", "Bright tunic", 320_000, "tunic"),
        ("Ayollar jinsisi skinny", "Женские скинни-джинсы", "Women's skinny jeans", 620_000, "jeans-women"),
        ("Levi's 501 Original Cropped", "Levi's 501 Original Cropped", "Levi's 501 Original Cropped", 750_000, "jeans-women"),
        ("Wide-leg jinsi", "Джинсы wide-leg", "Wide-leg jeans", 580_000, "jeans-women"),
        ("Leggings sport", "Спортивные лосины", "Sports leggings", 280_000, "leggings"),
        ("Yoga shimlari", "Леггинсы для йоги", "Yoga pants", 320_000, "yoga-pants"),
        ("Nike Air Force 1 Women", "Nike Air Force 1 женские", "Nike Air Force 1 Women", 1_650_000, "sneakers-women"),
        ("Nike Air Max 90 Women", "Nike Air Max 90 женские", "Nike Air Max 90 Women", 1_750_000, "sneakers-women"),
        ("Adidas Forum Low", "Adidas Forum Low", "Adidas Forum Low", 1_400_000, "sneakers-women"),
        ("Puma Cali Sport", "Puma Cali Sport", "Puma Cali Sport", 1_200_000, "sneakers-women"),
        ("Ayollar krossovkasi balet", "Балетки женские", "Women's ballet flats", 580_000, "ballet-flats"),
        ("Ayollar krasovkasi sport", "Женские кроссовки спортивные", "Women's sport sneakers", 950_000, "sneakers-women"),
        ("Yuqori poshnali tufli", "Туфли на высоком каблуке", "High-heel shoes", 720_000, "heels"),
        ("Ayollar sumkasi tote", "Женская сумка-тоут", "Women's tote bag", 720_000, "handbag"),
        ("Sumkacha bag clutch", "Клатч-сумка", "Clutch bag", 480_000, "clutch"),
        ("Yenfor cross-body sumka", "Сумка кросс-боди", "Cross-body bag", 540_000, "shoulder-bag"),
        ("Yelpig'ich rang-barang", "Шёлковый шарф", "Silk scarf", 280_000, "scarf"),
        ("Quyoshdan ko'zoynak", "Солнцезащитные очки", "Sunglasses", 380_000, "sunglasses"),
        ("Marvarid sirg'a", "Жемчужные серьги", "Pearl earrings", 280_000, "earrings"),
        ("Bilakuzuk kumush", "Серебряный браслет", "Silver bracelet", 420_000, "bracelet"),
        ("Marjon zanjir", "Цепочка серебряная", "Silver necklace", 380_000, "necklace"),
        ("Ayollar kashtanasi kurtka", "Женская осенняя куртка", "Women's autumn jacket", 980_000, "women-jacket"),
        ("Trench palto bej", "Бежевое пальто-тренч", "Beige trench coat", 1_400_000, "trench-coat"),
    ],

    # ========================================================================
    # KIYIM-KECHAK — Bolalar (~25)
    # ========================================================================
    "bolalar-kiyimi": [
        ("Bolalar krossovkasi Nike", "Детские кроссовки Nike", "Nike kids' sneakers", 850_000, "kids-shoes"),
        ("Adidas Disney bolalar", "Adidas Disney детские", "Adidas Disney kids", 920_000, "kids-shoes"),
        ("Puma bolalar krossovkasi", "Детские кроссовки Puma", "Puma kids' sneakers", 720_000, "kids-shoes"),
        ("Bolalar oddiy kedalari", "Детские простые кеды", "Kids' simple shoes", 320_000, "kids-shoes"),
        ("Bolalar sandallari", "Детские сандалии", "Kids' sandals", 280_000, "kids-sandals"),
        ("Maktab forma'si o'g'il bola", "Школьная форма для мальчика", "Boys' school uniform", 650_000, "school-uniform"),
        ("Maktab forma'si qiz bola", "Школьная форма для девочки", "Girls' school uniform", 680_000, "school-uniform"),
        ("Bolalar futbolkasi paxta", "Детская хлопковая футболка", "Kids' cotton T-shirt", 180_000, "kids-shirt"),
        ("Bolalar futbolkasi prints", "Детская футболка с принтом", "Kids' graphic T-shirt", 220_000, "kids-shirt"),
        ("Bolalar shimlari", "Детские штаны", "Kids' trousers", 240_000, "kids-pants"),
        ("Bolalar shorti", "Детские шорты", "Kids' shorts", 180_000, "kids-shorts"),
        ("Bolalar jinsi", "Детские джинсы", "Kids' jeans", 320_000, "kids-jeans"),
        ("Bolalar kurtkasi qish", "Детская зимняя куртка", "Kids' winter jacket", 580_000, "kids-jacket"),
        ("Bolalar yomg'irlik plashi", "Детский плащ-дождевик", "Kids' raincoat", 280_000, "raincoat"),
        ("Hoodie bolalar uchun", "Худи детское", "Kids' hoodie", 320_000, "kids-hoodie"),
        ("Bolalar tunika qiz uchun", "Туника детская для девочки", "Girls' tunic", 240_000, "kids-tunic"),
        ("Bolalar libosi qiz uchun", "Платье детское для девочки", "Girls' dress", 320_000, "kids-dress"),
        ("Bolalar bosh kiyimi", "Детская кепка", "Kids' cap", 120_000, "kids-cap"),
        ("Bolalar shapkasi qish", "Детская зимняя шапка", "Kids' winter hat", 180_000, "winter-hat"),
        ("Bolalar paypoq to'plami 5", "Детские носки 5 пар", "Kids' socks 5 pairs", 95_000, "kids-socks"),
        ("Pijama bolalar uchun", "Детская пижама", "Kids' pajamas", 280_000, "pajamas"),
        ("Bolalar palto qish", "Детское зимнее пальто", "Kids' winter coat", 720_000, "kids-coat"),
        ("Bolalar suzish sirti", "Детский купальный костюм", "Kids' swimwear", 220_000, "swimwear"),
        ("Bolalar sportiv kostyumi", "Детский спортивный костюм", "Kids' tracksuit", 380_000, "tracksuit"),
        ("Chaqaloq body to'plami", "Боди для малыша набор", "Baby bodysuit set", 320_000, "baby-bodysuit"),
    ],

    # ========================================================================
    # OZIQ-OVQAT — Mevalar (~25)
    # ========================================================================
    "mevalar": [
        ("Olma Simirenko 1kg", "Яблоки Семиренко 1кг", "Simirenko apples 1kg", 18_000, "apple-fruit"),
        ("Olma Granny Smith 1kg", "Яблоки Гренни Смит 1кг", "Granny Smith apples 1kg", 22_000, "apple-fruit"),
        ("Olma Fuji 1kg", "Яблоки Фуджи 1кг", "Fuji apples 1kg", 24_000, "apple-fruit"),
        ("Banan 1kg", "Бананы 1кг", "Bananas 1kg", 22_000, "banana"),
        ("Apelsin 1kg", "Апельсины 1кг", "Oranges 1kg", 25_000, "orange-fruit"),
        ("Mandarin 1kg", "Мандарины 1кг", "Mandarins 1kg", 28_000, "mandarin"),
        ("Limon 1kg", "Лимоны 1кг", "Lemons 1kg", 24_000, "lemon"),
        ("Greypfrut 1kg", "Грейпфрут 1кг", "Grapefruit 1kg", 32_000, "grapefruit"),
        ("Uzum Husayni 1kg", "Виноград Хусайни 1кг", "Husayni grapes 1kg", 32_000, "grapes"),
        ("Uzum Toyfi 1kg", "Виноград Тойфи 1кг", "Toyfi grapes 1kg", 28_000, "grapes"),
        ("Uzum qora 1kg", "Виноград чёрный 1кг", "Black grapes 1kg", 35_000, "grapes"),
        ("Anor 1kg", "Гранат 1кг", "Pomegranate 1kg", 28_000, "pomegranate"),
        ("Qulupnay 500g", "Клубника 500г", "Strawberry 500g", 35_000, "strawberry"),
        ("Olcha 1kg", "Черешня 1кг", "Cherries 1kg", 42_000, "cherry"),
        ("Olxo'ri 1kg", "Слива 1кг", "Plums 1kg", 28_000, "plum"),
        ("Shaftoli 1kg", "Персики 1кг", "Peaches 1kg", 32_000, "peach"),
        ("Nok 1kg", "Груши 1кг", "Pears 1kg", 26_000, "pear"),
        ("O'rik 1kg", "Абрикосы 1кг", "Apricots 1kg", 28_000, "apricot"),
        ("Anjir 1kg", "Инжир 1кг", "Figs 1kg", 42_000, "figs"),
        ("Tarvuz 1kg", "Арбуз 1кг", "Watermelon 1kg", 12_000, "watermelon"),
        ("Qovun 1kg", "Дыня 1кг", "Melon 1kg", 14_000, "melon"),
        ("Avokado dona", "Авокадо 1шт", "Avocado 1 pc", 22_000, "avocado"),
        ("Manggo 1kg", "Манго 1кг", "Mango 1kg", 65_000, "mango"),
        ("Ananas 1 dona", "Ананас 1шт", "Pineapple 1 pc", 45_000, "pineapple"),
        ("Quritilgan mevalar to'plami", "Сухофрукты ассорти", "Dried fruit assortment", 75_000, "dried-fruit"),
    ],

    # ========================================================================
    # OZIQ-OVQAT — Ichimliklar (~25)
    # ========================================================================
    "ichimliklar": [
        ("Coca-Cola 1.5L", "Coca-Cola 1.5л", "Coca-Cola 1.5L", 14_000, "cola"),
        ("Coca-Cola Zero 1.5L", "Coca-Cola Zero 1.5л", "Coca-Cola Zero 1.5L", 14_000, "cola"),
        ("Pepsi 1.5L", "Pepsi 1.5л", "Pepsi 1.5L", 13_000, "soda"),
        ("Fanta apelsin 1.5L", "Fanta апельсин 1.5л", "Fanta orange 1.5L", 13_000, "soda"),
        ("Sprite 1.5L", "Sprite 1.5л", "Sprite 1.5L", 13_000, "soda"),
        ("Tabiiy suv 5L", "Минеральная вода 5л", "Mineral water 5L", 9_000, "water-bottle"),
        ("Tabiiy suv 1.5L", "Минеральная вода 1.5л", "Mineral water 1.5L", 5_000, "water-bottle"),
        ("Gazli suv Borjomi 0.5L", "Боржоми газированная 0.5л", "Borjomi sparkling 0.5L", 18_000, "sparkling-water"),
        ("Apelsin sharbati 1L", "Апельсиновый сок 1л", "Orange juice 1L", 18_000, "juice"),
        ("Olma sharbati 1L", "Яблочный сок 1л", "Apple juice 1L", 16_000, "juice"),
        ("Sabzavot sharbati 1L", "Овощной сок 1л", "Vegetable juice 1L", 22_000, "juice"),
        ("Choy Lipton 100 paket", "Чай Lipton 100 пак.", "Lipton tea 100 bags", 38_000, "tea"),
        ("Choy Greenfield 100 paket", "Чай Greenfield 100 пак.", "Greenfield tea 100 bags", 45_000, "tea"),
        ("Yashil choy Ahmad 100 paket", "Зелёный чай Ahmad 100 пак.", "Ahmad green tea 100 bags", 42_000, "green-tea"),
        ("Qahva Jacobs Monarch 200g", "Кофе Jacobs Monarch 200г", "Jacobs Monarch coffee 200g", 65_000, "coffee"),
        ("Qahva Nescafe Gold 100g", "Кофе Nescafe Gold 100г", "Nescafe Gold coffee 100g", 78_000, "coffee"),
        ("Qahva donalari Lavazza 1kg", "Кофе в зёрнах Lavazza 1кг", "Lavazza coffee beans 1kg", 240_000, "coffee-beans"),
        ("Red Bull Energy 250ml", "Red Bull Energy 250мл", "Red Bull Energy 250ml", 22_000, "energy-drink"),
        ("Monster Energy 500ml", "Monster Energy 500мл", "Monster Energy 500ml", 25_000, "energy-drink"),
        ("Adrenaline Rush 0.5L", "Adrenaline Rush 0.5л", "Adrenaline Rush 0.5L", 18_000, "energy-drink"),
        ("Sut Toza 1L", "Молоко Toza 1л", "Toza milk 1L", 14_000, "milk"),
        ("Yogurt natural 0.5L", "Натуральный йогурт 0.5л", "Natural yogurt 0.5L", 16_000, "yogurt"),
        ("Aryan 0.5L", "Айран 0.5л", "Aryan 0.5L", 8_000, "ayran"),
        ("Limonad ev tarzi", "Домашний лимонад", "Homemade lemonade", 22_000, "lemonade"),
        ("Mors qulupnay 1L", "Морс клубничный 1л", "Strawberry mors 1L", 24_000, "berry-drink"),
    ],

    # ========================================================================
    # OZIQ-OVQAT — Shirinliklar (~25)
    # ========================================================================
    "shirinliklar": [
        ("Shokolad Alpen Gold 100g", "Шоколад Alpen Gold 100г", "Alpen Gold chocolate 100g", 18_000, "chocolate"),
        ("Shokolad Milka 100g", "Шоколад Milka 100г", "Milka chocolate 100g", 22_000, "chocolate"),
        ("Shokolad Ritter Sport", "Шоколад Ritter Sport", "Ritter Sport chocolate", 28_000, "chocolate"),
        ("Shokolad Lindt Excellence 70%", "Шоколад Lindt Excellence 70%", "Lindt Excellence 70% chocolate", 65_000, "chocolate"),
        ("Shokolad Toblerone 100g", "Шоколад Toblerone 100г", "Toblerone chocolate 100g", 32_000, "chocolate"),
        ("Shokolad assorti 400g Nestle", "Шоколад ассорти 400г Nestle", "Nestle chocolate assortment 400g", 65_000, "chocolate"),
        ("Pechenye Yubileynoe 300g", "Печенье Юбилейное 300г", "Yubileynoye cookies 300g", 22_000, "cookies"),
        ("Pechenye Oreo 144g", "Печенье Oreo 144г", "Oreo cookies 144g", 18_000, "cookies"),
        ("Pechenye TUC 100g", "Печенье TUC 100г", "TUC crackers 100g", 12_000, "crackers"),
        ("Vafli Yashka", "Вафли Яшка", "Yashka waffles", 14_000, "waffles"),
        ("Tort Napoleon", "Торт Наполеон", "Napoleon cake", 95_000, "cake"),
        ("Tort Medovik", "Торт Медовик", "Medovik cake", 85_000, "cake"),
        ("Cheesecake muzlatilgan", "Чизкейк замороженный", "Frozen cheesecake", 110_000, "cheesecake"),
        ("Tiramisu 500g", "Тирамису 500г", "Tiramisu 500g", 120_000, "tiramisu"),
        ("Tort shokolad 500g", "Шоколадный торт 500г", "Chocolate cake 500g", 95_000, "chocolate-cake"),
        ("Halva yong'oqli 500g", "Халва ореховая 500г", "Walnut halva 500g", 32_000, "halva"),
        ("Halva oddiy 500g", "Халва обычная 500г", "Plain halva 500g", 28_000, "halva"),
        ("Konfet Korovka 250g", "Конфеты Коровка 250г", "Korovka candy 250g", 24_000, "candy"),
        ("Konfet Snickers Mini 200g", "Конфеты Snickers Mini 200г", "Snickers Mini candy 200g", 38_000, "candy"),
        ("Konfet Raffaello 150g", "Конфеты Raffaello 150г", "Raffaello candy 150g", 65_000, "candy"),
        ("Marmelad bolalar uchun", "Мармелад детский", "Kids' marmalade", 18_000, "candy"),
        ("Zefir oddiy 200g", "Зефир 200г", "Zefir 200g", 22_000, "zefir"),
        ("Marshmallow 100g", "Маршмеллоу 100г", "Marshmallow 100g", 26_000, "marshmallow"),
        ("Donut to'plami 6 dona", "Пончики 6 шт", "Donuts 6 pcs", 48_000, "donut"),
        ("Croissant 100g", "Круассан 100г", "Croissant 100g", 14_000, "croissant"),
    ],

    # ========================================================================
    # GO'ZALLIK — Parfyumeriya (~20)
    # ========================================================================
    "parfyumeriya": [
        ("Chanel No. 5 EDP 50ml", "Chanel No. 5 EDP 50мл", "Chanel No. 5 EDP 50ml", 1_800_000, "perfume"),
        ("Chanel Coco Mademoiselle 50ml", "Chanel Coco Mademoiselle 50мл", "Chanel Coco Mademoiselle 50ml", 1_650_000, "perfume"),
        ("Dior Sauvage EDT 100ml", "Dior Sauvage EDT 100мл", "Dior Sauvage EDT 100ml", 1_400_000, "cologne"),
        ("Dior J'adore 50ml", "Dior J'adore 50мл", "Dior J'adore 50ml", 1_550_000, "perfume"),
        ("YSL Black Opium 50ml", "YSL Black Opium 50мл", "YSL Black Opium 50ml", 1_350_000, "perfume"),
        ("YSL Libre 50ml", "YSL Libre 50мл", "YSL Libre 50ml", 1_290_000, "perfume"),
        ("Tom Ford Black Orchid 50ml", "Tom Ford Black Orchid 50мл", "Tom Ford Black Orchid 50ml", 2_100_000, "perfume"),
        ("Tom Ford Tobacco Vanille", "Tom Ford Tobacco Vanille", "Tom Ford Tobacco Vanille", 2_400_000, "perfume"),
        ("Versace Eros 100ml", "Versace Eros 100мл", "Versace Eros 100ml", 980_000, "cologne"),
        ("Hugo Boss Bottled 100ml", "Hugo Boss Bottled 100мл", "Hugo Boss Bottled 100ml", 820_000, "cologne"),
        ("Calvin Klein One 100ml", "Calvin Klein One 100мл", "Calvin Klein One 100ml", 620_000, "cologne"),
        ("Lacoste L.12.12 100ml", "Lacoste L.12.12 100мл", "Lacoste L.12.12 100ml", 680_000, "cologne"),
        ("Giorgio Armani Acqua di Gio", "Giorgio Armani Acqua di Gio", "Giorgio Armani Acqua di Gio", 1_100_000, "cologne"),
        ("Paco Rabanne 1 Million", "Paco Rabanne 1 Million", "Paco Rabanne 1 Million", 950_000, "cologne"),
        ("Lancome La Vie Est Belle", "Lancome La Vie Est Belle", "Lancome La Vie Est Belle", 1_280_000, "perfume"),
        ("Guerlain Mon Guerlain", "Guerlain Mon Guerlain", "Guerlain Mon Guerlain", 1_350_000, "perfume"),
        ("Carolina Herrera Good Girl", "Carolina Herrera Good Girl", "Carolina Herrera Good Girl", 1_180_000, "perfume"),
        ("Yog'li atir 30ml universal", "Масляный парфюм 30мл", "Oil perfume 30ml", 180_000, "oil-perfume"),
        ("Erkaklar atiri sandal", "Мужской парфюм сандал", "Men's sandalwood cologne", 540_000, "cologne"),
        ("Solid perfume balm", "Твёрдый парфюм", "Solid perfume balm", 220_000, "solid-perfume"),
    ],

    # ========================================================================
    # GO'ZALLIK — Kosmetika (~30)
    # ========================================================================
    "kosmetika": [
        ("L'Oreal Yuz kremi gigartik", "L'Oreal крем для лица", "L'Oreal face cream", 145_000, "face-cream"),
        ("L'Oreal Revitalift krem", "L'Oreal Revitalift крем", "L'Oreal Revitalift cream", 195_000, "face-cream"),
        ("Garnier Hyaluronik krem", "Garnier гиалуроновый крем", "Garnier hyaluronic cream", 125_000, "face-cream"),
        ("Nivea ko'k krem 250ml", "Крем NIVEA 250мл", "NIVEA blue cream 250ml", 65_000, "moisturizer"),
        ("CeraVe Yuz tozalovchi gel", "CeraVe гель для умывания", "CeraVe face cleanser", 220_000, "face-cleanser"),
        ("Estée Lauder Advanced Night Repair", "Estée Lauder Advanced Night Repair", "Estée Lauder Advanced Night Repair", 1_240_000, "serum"),
        ("The Ordinary Niacinamide 10%", "The Ordinary Niacinamide 10%", "The Ordinary Niacinamide 10%", 145_000, "serum"),
        ("La Roche-Posay Effaclar gel", "La Roche-Posay Effaclar gel", "La Roche-Posay Effaclar gel", 195_000, "face-wash"),
        ("L'Oreal Lab bo'yog'i to'plami", "L'Oreal набор помад", "L'Oreal lipstick set", 230_000, "lipstick"),
        ("MAC Lab bo'yog'i ruby woo", "MAC помада Ruby Woo", "MAC Ruby Woo lipstick", 320_000, "lipstick"),
        ("Maybelline Superstay lab bo'yog'i", "Maybelline Superstay помада", "Maybelline Superstay lipstick", 145_000, "lipstick"),
        ("Lab balzami EOS", "Бальзам для губ EOS", "EOS lip balm", 45_000, "lip-balm"),
        ("Vaseline Lab balzami", "Бальзам для губ Vaseline", "Vaseline lip balm", 28_000, "lip-balm"),
        ("Maybelline Tush ko'z uchun Lash Sensational", "Maybelline тушь Lash Sensational", "Maybelline Lash Sensational mascara", 85_000, "mascara"),
        ("Loreal Tush Telescopic", "L'Oreal тушь Telescopic", "L'Oreal Telescopic mascara", 95_000, "mascara"),
        ("Maybelline Tonal krem Fit Me", "Maybelline тональный крем Fit Me", "Maybelline Fit Me foundation", 145_000, "foundation"),
        ("Loreal True Match Tonal", "L'Oreal True Match", "L'Oreal True Match foundation", 195_000, "foundation"),
        ("NARS Concealer", "NARS консилер", "NARS concealer", 320_000, "concealer"),
        ("Urban Decay Naked palette", "Urban Decay Naked палитра", "Urban Decay Naked palette", 480_000, "eyeshadow"),
        ("Maybelline Color Sensational palette", "Maybelline Color Sensational", "Maybelline Color Sensational", 180_000, "eyeshadow"),
        ("Loreal True Match Bronzer", "L'Oreal Bronzer", "L'Oreal bronzer", 145_000, "bronzer"),
        ("NYX Pro Highlighter", "NYX хайлайтер", "NYX Pro Highlighter", 95_000, "highlighter"),
        ("Yuz qizillaytiruvchi blush", "Румяна для щек", "Face blush", 85_000, "blush"),
        ("Sephora kistlar to'plami", "Sephora набор кистей", "Sephora brush set", 320_000, "makeup-brush"),
        ("Beautyblender sponge", "Beautyblender спонж", "Beautyblender sponge", 145_000, "makeup-sponge"),
        ("Garnier Sheet maska", "Garnier маска-салфетка", "Garnier sheet mask", 28_000, "sheet-mask"),
        ("Tony Moly maska to'plami", "Tony Moly набор масок", "Tony Moly mask set", 145_000, "face-mask"),
        ("Bioderma Sensibio sutmoq", "Bioderma Sensibio тоник", "Bioderma Sensibio toner", 165_000, "toner"),
        ("Pixi Glow Tonik", "Pixi Glow Tonic", "Pixi Glow Tonic", 220_000, "toner"),
        ("Sunscreen SPF 50 Garnier", "Garnier солнцезащитный SPF 50", "Garnier SPF 50 sunscreen", 135_000, "sunscreen"),
    ],

    # ========================================================================
    # UY VA BOG' — Oshxona (~30)
    # ========================================================================
    "oshxona": [
        ("Bosch Changyutgich BGS5", "Пылесос Bosch BGS5", "Bosch BGS5 vacuum cleaner", 3_400_000, "vacuum"),
        ("Dyson V12 Detect", "Dyson V12 Detect", "Dyson V12 Detect", 9_800_000, "vacuum"),
        ("Xiaomi Mi Robot vacuum", "Xiaomi Mi Robot пылесос", "Xiaomi Mi Robot vacuum", 4_200_000, "robot-vacuum"),
        ("Philips Dazmoli Azur 8000", "Утюг Philips Azur 8000", "Philips Azur 8000 iron", 850_000, "iron-appliance"),
        ("Tefal Dazmoli", "Утюг Tefal", "Tefal iron", 620_000, "iron-appliance"),
        ("Choynak elektr Bosch 1.7L", "Электрический чайник Bosch 1.7л", "Bosch electric kettle 1.7L", 480_000, "kettle"),
        ("Choynak Tefal 1.5L", "Чайник Tefal 1.5л", "Tefal kettle 1.5L", 380_000, "kettle"),
        ("Multivarka Redmond 5L", "Мультиварка Redmond 5л", "Redmond multicooker 5L", 1_450_000, "multicooker"),
        ("Polaris Multivarka", "Polaris мультиварка", "Polaris multicooker", 950_000, "multicooker"),
        ("Blender Philips HR2535", "Блендер Philips HR2535", "Philips HR2535 blender", 580_000, "blender"),
        ("Blender NutriBullet", "Блендер NutriBullet", "NutriBullet blender", 980_000, "blender"),
        ("Mikser KitchenAid", "Миксер KitchenAid", "KitchenAid mixer", 3_200_000, "mixer"),
        ("Mikrovolnoviy LG NeoChef", "Микроволновка LG NeoChef", "LG NeoChef microwave", 1_400_000, "microwave"),
        ("Samsung Mikrovolnoviy 23L", "Микроволновка Samsung 23л", "Samsung microwave 23L", 1_180_000, "microwave"),
        ("Qahva mashinasi DeLonghi", "Кофемашина DeLonghi", "DeLonghi coffee machine", 4_500_000, "coffee-machine"),
        ("Qahva mashinasi Bosch", "Кофемашина Bosch", "Bosch coffee machine", 3_800_000, "coffee-machine"),
        ("Tovoq to'plami 12 dona chinni", "Набор тарелок 12 шт фарфор", "Porcelain plate set 12 pcs", 480_000, "dishes"),
        ("Stakanlar to'plami 6 dona", "Набор стаканов 6 шт", "Glass set 6 pcs", 180_000, "glasses"),
        ("Pichoq to'plami Tramontina", "Набор ножей Tramontina", "Tramontina knife set", 620_000, "knives"),
        ("Pichoq professional Wusthof", "Профессиональный нож Wusthof", "Wusthof professional knife", 1_280_000, "knives"),
        ("Patelnya 28cm Tefal", "Сковорода 28см Tefal", "Tefal 28cm pan", 420_000, "pan"),
        ("Kazan 5L cho'yan", "Казан 5л чугунный", "Cast iron pot 5L", 580_000, "cast-iron"),
        ("Sushilka Bosch idishlar", "Сушка для посуды Bosch", "Bosch dish dryer", 380_000, "dish-dryer"),
        ("Idishlar yuvgich Bosch", "Посудомоечная машина Bosch", "Bosch dishwasher", 5_400_000, "dishwasher"),
        ("Muzlatgich Samsung 350L", "Холодильник Samsung 350л", "Samsung fridge 350L", 6_200_000, "fridge"),
        ("Muzlatgich LG 450L", "Холодильник LG 450л", "LG fridge 450L", 7_800_000, "fridge"),
        ("Termos 1L Stanley", "Термос Stanley 1л", "Stanley thermos 1L", 380_000, "thermos"),
        ("Termobardak 500ml", "Термокружка 500мл", "Thermal mug 500ml", 145_000, "thermal-mug"),
        ("Salfetka 100 dona", "Салфетки 100 шт", "Napkins 100 pcs", 28_000, "napkins"),
        ("Oziq-ovqat saqlash konteyneri", "Контейнеры для еды набор", "Food storage containers set", 220_000, "food-container"),
    ],

    # ========================================================================
    # UY VA BOG' — Tekstil (~20)
    # ========================================================================
    "tekstil": [
        ("Ko'rpa-to'shak to'plami 2 kishilik", "Комплект постельного белья 2-сп", "Bedding set 2-person", 650_000, "bedding"),
        ("Ko'rpa-to'shak Euro xach 2x2", "КПБ Евро 2x2", "Euro bedding 2x2", 820_000, "bedding"),
        ("Bolalar uchun ko'rpa-to'shak", "Детский комплект постельного белья", "Kids' bedding set", 420_000, "kids-bedding"),
        ("Sochiq to'plami 4 dona", "Набор полотенец 4 шт", "Towel set 4 pcs", 180_000, "towels"),
        ("Hammom sochig'i katta", "Большое банное полотенце", "Large bath towel", 220_000, "bath-towel"),
        ("Plyaj sochig'i", "Пляжное полотенце", "Beach towel", 180_000, "beach-towel"),
        ("Yopinchi gilam yumshoq", "Декоративный плед", "Decorative blanket", 320_000, "blanket"),
        ("Ko'rpa zima 2 kishilik", "Зимнее одеяло 2-сп", "Winter blanket 2-person", 580_000, "winter-blanket"),
        ("Yostiq pero 50x70", "Подушка перо 50x70", "Feather pillow 50x70", 220_000, "pillow"),
        ("Anti-allergen yostiq", "Антиаллергенная подушка", "Hypoallergenic pillow", 320_000, "pillow"),
        ("Yostiq qopi 2 dona", "Наволочки 2 шт", "Pillowcase 2 pcs", 65_000, "pillowcase"),
        ("Tutqich pardalari", "Шторы для гостиной", "Living room curtains", 720_000, "curtains"),
        ("Pardalar oshxonaga", "Шторы для кухни", "Kitchen curtains", 320_000, "curtains"),
        ("Tul oq", "Тюль белая", "White tulle", 280_000, "tulle"),
        ("Stol o'lcham 6 kishilik", "Скатерть на 6 человек", "Tablecloth for 6", 220_000, "tablecloth"),
        ("Gilam yumshoq 2x3m", "Мягкий ковёр 2x3м", "Soft carpet 2x3m", 1_400_000, "carpet"),
        ("Gilam yo'lakcha", "Ковёр-дорожка", "Carpet runner", 480_000, "rug-runner"),
        ("Sumka jovardonlar uchun", "Сумка для постельного белья", "Bedding storage bag", 95_000, "storage-bag"),
        ("Yotgan to'shak protektor", "Защитный наматрасник", "Mattress protector", 280_000, "mattress-pad"),
        ("Mahalliy adyol koshma", "Узбекское одеяло-кошма", "Uzbek koshma blanket", 420_000, "wool-blanket"),
    ],

    # ========================================================================
    # BOLALAR — O'yinchoqlar (~30)
    # ========================================================================
    "oyinchoqlar": [
        ("Lego Classic 500 detal", "Lego Classic 500 деталей", "Lego Classic 500 pieces", 420_000, "lego"),
        ("Lego Technic Bugatti Chiron", "Lego Technic Bugatti Chiron", "Lego Technic Bugatti Chiron", 1_800_000, "lego"),
        ("Lego City Politsiya stansiyasi", "Lego City Полицейский участок", "Lego City Police Station", 850_000, "lego"),
        ("Lego Star Wars Death Star", "Lego Star Wars Death Star", "Lego Star Wars Death Star", 2_200_000, "lego"),
        ("Lego Friends restoran", "Lego Friends Ресторан", "Lego Friends Restaurant", 680_000, "lego"),
        ("Lego Duplo bolalar 2+", "Lego Duplo 2+", "Lego Duplo 2+", 380_000, "lego"),
        ("Masofadan boshqariladigan mashina", "Радиоуправляемая машина", "Remote-control car", 280_000, "toy-car"),
        ("Drift mashinasi RC 1:14", "Дрифт-машина RC 1:14", "RC drift car 1:14", 580_000, "rc-car"),
        ("Yumshoq o'yinchoq ayiq 50sm", "Плюшевый медведь 50см", "Teddy bear 50cm", 220_000, "teddy-bear"),
        ("Yumshoq o'yinchoq sherbat 80sm", "Плюшевый зайчик 80см", "Plush bunny 80cm", 320_000, "plush-toy"),
        ("Yumshoq itcha katta", "Большая плюшевая собака", "Large plush dog", 380_000, "plush-toy"),
        ("Konstruktor magnit 100 detal", "Магнитный конструктор 100 дет.", "Magnetic blocks 100 pcs", 480_000, "magnetic-blocks"),
        ("Konstruktor blok 300 detal", "Конструктор 300 деталей", "Building blocks 300 pcs", 195_000, "blocks"),
        ("Qo'g'irchoq Barbie", "Кукла Barbie", "Barbie doll", 220_000, "doll"),
        ("Qo'g'irchoq L.O.L. Surprise", "Кукла L.O.L. Surprise", "L.O.L. Surprise doll", 280_000, "doll"),
        ("Qo'g'irchoqlar to'plami 5 ta", "Набор кукол 5 шт", "Doll set 5 pcs", 320_000, "dolls"),
        ("Pleymobil 100 detal", "Playmobil 100 деталей", "Playmobil 100 pcs", 420_000, "playmobil"),
        ("Hot Wheels mashinalar to'plami", "Hot Wheels набор машин", "Hot Wheels car set", 145_000, "hot-wheels"),
        ("Hot Wheels trek Mega Garage", "Hot Wheels трек Mega Garage", "Hot Wheels Mega Garage track", 580_000, "racing-track"),
        ("Bolalar piyaningi 2-7 yosh", "Детский батут 2-7 лет", "Kids' trampoline 2-7 yrs", 480_000, "trampoline"),
        ("Bolalar samokati", "Детский самокат", "Kids' scooter", 380_000, "kids-scooter"),
        ("Velosiped bolalarga 16\"", "Детский велосипед 16\"", "Kids' bike 16\"", 1_200_000, "kids-bike"),
        ("Puzzle 1000 detal Disney", "Пазл 1000 деталей Disney", "Disney puzzle 1000 pcs", 145_000, "puzzle"),
        ("Puzzle 500 detal", "Пазл 500 деталей", "Puzzle 500 pcs", 95_000, "puzzle"),
        ("Stol o'yini Monopoly", "Настольная игра Монополия", "Monopoly board game", 220_000, "board-game"),
        ("Stol o'yini UNO", "Настольная игра UNO", "UNO board game", 65_000, "board-game"),
        ("Bolalar pianino", "Детское пианино", "Kids' piano", 480_000, "kids-piano"),
        ("Bolalar gitara", "Детская гитара", "Kids' guitar", 320_000, "kids-guitar"),
        ("O'yinchoq Avtomobil-Garage", "Игрушка автомобиль-гараж", "Toy car garage", 280_000, "toy-garage"),
        ("Slime to'plami 6 dona", "Слайм набор 6 шт", "Slime set 6 pcs", 85_000, "slime"),
    ],

    # ========================================================================
    # SPORT (~35)
    # ========================================================================
    "sport": [
        ("Dumbbell to'plami 20kg cho'yan", "Гантели 20кг чугунные", "Dumbbell set 20kg cast iron", 1_200_000, "dumbbell"),
        ("Dumbbell to'plami 30kg", "Гантели 30кг", "Dumbbell set 30kg", 1_650_000, "dumbbell"),
        ("Stoyka 100kg shtanga", "Штанга со стойкой 100кг", "100kg barbell with stand", 4_200_000, "barbell"),
        ("Kettlebell 16kg", "Гиря 16кг", "Kettlebell 16kg", 480_000, "kettlebell"),
        ("Yoga gilam Pro 6mm", "Коврик для йоги Pro 6мм", "Yoga mat Pro 6mm", 350_000, "yoga-mat"),
        ("Yoga gilam premium 8mm", "Коврик для йоги премиум 8мм", "Premium yoga mat 8mm", 480_000, "yoga-mat"),
        ("Yoga to'plami (gilam+blok)", "Набор для йоги (коврик+блок)", "Yoga set (mat+block)", 580_000, "yoga-set"),
        ("Yoga bloki EVA", "Блок для йоги EVA", "EVA yoga block", 95_000, "yoga-block"),
        ("Velosiped Mountain Trinx", "Велосипед Mountain Trinx", "Trinx Mountain bike", 3_200_000, "bicycle"),
        ("Velosiped shaharlik 26\"", "Городской велосипед 26\"", "City bike 26\"", 2_400_000, "bicycle"),
        ("Velosiped sport BMX", "Спортивный велосипед BMX", "BMX sport bike", 1_800_000, "bmx-bike"),
        ("Velosiped elektr Xiaomi", "Электровелосипед Xiaomi", "Xiaomi e-bike", 6_500_000, "ebike"),
        ("Skateboard professional", "Скейтборд профессиональный", "Pro skateboard", 720_000, "skateboard"),
        ("Roller konki M (39-42)", "Роликовые коньки M", "Roller skates M (39-42)", 480_000, "roller-skates"),
        ("Futbol to'pi Adidas Tango", "Футбольный мяч Adidas Tango", "Adidas Tango football", 280_000, "football"),
        ("Futbol to'pi Nike Pro", "Футбольный мяч Nike Pro", "Nike Pro football", 320_000, "football"),
        ("Basketbol to'pi Spalding", "Баскетбольный мяч Spalding", "Spalding basketball", 380_000, "basketball"),
        ("Voleybol to'pi Mikasa", "Волейбольный мяч Mikasa", "Mikasa volleyball", 320_000, "volleyball"),
        ("Tennis raketkasi Wilson", "Теннисная ракетка Wilson", "Wilson tennis racket", 580_000, "tennis-racket"),
        ("Tennis to'pi Wilson 3 dona", "Теннисные мячи Wilson 3 шт", "Wilson tennis balls 3 pcs", 95_000, "tennis-ball"),
        ("Badminton to'plami", "Набор для бадминтона", "Badminton set", 220_000, "badminton"),
        ("Sport sumkasi Nike", "Спортивная сумка Nike", "Nike sports bag", 380_000, "gym-bag"),
        ("Sport sumkasi Adidas Duffel", "Спортивная сумка Adidas Duffel", "Adidas Duffel bag", 420_000, "duffel-bag"),
        ("Bokserlik qo'lqop Everlast", "Боксёрские перчатки Everlast", "Everlast boxing gloves", 420_000, "boxing-gloves"),
        ("Bokserlik qop 60kg", "Боксёрский мешок 60кг", "Boxing bag 60kg", 1_400_000, "boxing-bag"),
        ("Sakraydigan arqon", "Скакалка скоростная", "Speed jump rope", 95_000, "jump-rope"),
        ("Fitnes lenta to'plami 5", "Фитнес-резинки набор 5шт", "Fitness band set 5", 145_000, "resistance-band"),
        ("Sport ko'ylakcha Nike Dri-FIT", "Спортивная футболка Nike Dri-FIT", "Nike Dri-FIT sports T-shirt", 280_000, "sports-shirt"),
        ("Sport shorti Adidas", "Спортивные шорты Adidas", "Adidas sports shorts", 220_000, "sports-shorts"),
        ("Sport leggings Reebok", "Спортивные леггинсы Reebok", "Reebok sports leggings", 380_000, "leggings"),
        ("Kompresion mayka", "Компрессионная майка", "Compression shirt", 280_000, "compression-shirt"),
        ("Suzish ko'zoynagi", "Очки для плавания", "Swimming goggles", 145_000, "swim-goggles"),
        ("Suzish shapkasi", "Шапочка для плавания", "Swimming cap", 65_000, "swim-cap"),
        ("Treadmill Xiaomi", "Беговая дорожка Xiaomi", "Xiaomi treadmill", 5_400_000, "treadmill"),
        ("Velotrenajor magnit", "Магнитный велотренажёр", "Magnetic exercise bike", 3_200_000, "exercise-bike"),
    ],

    # ========================================================================
    # KITOBLAR (~25)
    # ========================================================================
    "kitoblar": [
        ("Atomic Habits — uzbek tilida", "Атомные привычки", "Atomic Habits", 85_000, "book"),
        ("Boy ota, kambag'al ota", "Богатый папа, бедный папа", "Rich Dad Poor Dad", 72_000, "books"),
        ("O'tkan kunlar — A. Qodiriy", "Минувшие дни — А. Кадыри", "Days Gone By — A. Qadiri", 65_000, "old-book"),
        ("Mehrobdan chayon — A. Qodiriy", "Скорпион из алтаря — Кадыри", "Scorpion from the Altar — Qadiri", 58_000, "old-book"),
        ("Sariq devni minib", "Жёлтый див", "The Yellow Demon", 52_000, "novel"),
        ("Zero to One — Peter Thiel", "От нуля к единице", "Zero to One", 95_000, "business-book"),
        ("The Lean Startup", "Бережливый стартап", "The Lean Startup", 78_000, "business-book"),
        ("Sapiens — Y. N. Harari", "Sapiens — Ю. Н. Харари", "Sapiens — Y. N. Harari", 105_000, "history-book"),
        ("Homo Deus — Y. N. Harari", "Homo Deus — Ю. Н. Харари", "Homo Deus — Y. N. Harari", 110_000, "history-book"),
        ("21 Lessons for the 21st Century", "21 урок для XXI века", "21 Lessons for the 21st Century", 95_000, "history-book"),
        ("Tafakkur tezligi", "Скорость мышления", "Speed of Thought", 78_000, "thinking-book"),
        ("Think Fast and Slow", "Думай медленно... решай быстро", "Thinking, Fast and Slow", 120_000, "thinking-book"),
        ("Deep Work — Cal Newport", "Гениально просто! — Кэл Ньюпорт", "Deep Work — Cal Newport", 92_000, "business-book"),
        ("How to Win Friends and Influence People", "Как завоёвывать друзей", "How to Win Friends and Influence People", 85_000, "self-help-book"),
        ("The 7 Habits of Highly Effective People", "7 навыков высокоэффективных людей", "The 7 Habits of Highly Effective People", 95_000, "self-help-book"),
        ("Harry Potter va Falsafiy tosh", "Гарри Поттер и философский камень", "Harry Potter and the Philosopher's Stone", 145_000, "novel"),
        ("1984 — George Orwell", "1984 — Джордж Оруэлл", "1984 — George Orwell", 72_000, "novel"),
        ("Animal Farm", "Скотный двор", "Animal Farm", 58_000, "novel"),
        ("Bobillarning eng badavlat odami", "Самый богатый человек в Вавилоне", "The Richest Man in Babylon", 65_000, "business-book"),
        ("Clean Code — Robert Martin", "Чистый код — Роберт Мартин", "Clean Code — Robert Martin", 165_000, "tech-book"),
        ("Pragmatic Programmer", "Программист-прагматик", "The Pragmatic Programmer", 145_000, "tech-book"),
        ("Bolalar ertaklari to'plami", "Сборник детских сказок", "Children's fairy tales collection", 85_000, "kids-book"),
        ("Mole's Beautiful Garden", "Прекрасный сад крота", "Mole's Beautiful Garden", 65_000, "kids-book"),
        ("Coding for Kids — Python", "Программирование для детей Python", "Coding for Kids — Python", 95_000, "kids-book"),
        ("Cookbook traditional uzbek", "Кулинарная книга узбекская", "Uzbek cookbook", 145_000, "cookbook"),
    ],

    # ========================================================================
    # AVTOTOVARLAR (~25)
    # ========================================================================
    "avtotovarlar": [
        ("Motor moyi 4L Mobil 1 5W-30", "Моторное масло Mobil 1 5W-30 4л", "Mobil 1 5W-30 motor oil 4L", 380_000, "motor-oil"),
        ("Motor moyi 4L Castrol Edge", "Моторное масло Castrol Edge 4л", "Castrol Edge motor oil 4L", 420_000, "motor-oil"),
        ("Motor moyi Liqui Moly 5L", "Моторное масло Liqui Moly 5л", "Liqui Moly motor oil 5L", 580_000, "motor-oil"),
        ("Avtomobil shinasi R16 yozgi", "Автошина R16 летняя", "R16 summer tire", 750_000, "car-tire"),
        ("Avtoshina R17 qishki", "Автошина R17 зимняя", "R17 winter tire", 920_000, "car-tire"),
        ("Avtoshina Michelin R18", "Michelin R18", "Michelin R18", 1_400_000, "car-tire"),
        ("Avtomobil akkumulyatori 60Ah", "Автомобильный аккумулятор 60Ач", "Car battery 60Ah", 950_000, "car-battery"),
        ("Avtomobil akkumulyatori 75Ah", "Автомобильный аккумулятор 75Ач", "Car battery 75Ah", 1_240_000, "car-battery"),
        ("Salon gilami yog'och kilim", "Коврики салона еврочехлы", "Eurochehol floor mats", 580_000, "floor-mat"),
        ("Salon gilami silikon to'plam", "Силиконовые коврики набор", "Silicone floor mat set", 320_000, "floor-mat"),
        ("Avtomagnitola Pioneer 1DIN", "Автомагнитола Pioneer 1DIN", "Pioneer 1DIN car stereo", 540_000, "car-radio"),
        ("Avtomagnitola 2DIN Android", "Автомагнитола 2DIN Android", "2DIN Android car stereo", 1_400_000, "car-radio"),
        ("Avtomobil videoregistratori", "Автомобильный видеорегистратор", "Car dashcam", 480_000, "dashcam"),
        ("GPS-navigator Garmin", "GPS-навигатор Garmin", "Garmin GPS navigator", 1_800_000, "gps"),
        ("Avtomobil yopgich Yorqin", "Чехол на автомобиль", "Car cover", 480_000, "car-cover"),
        ("Avtomobil shini kompressori", "Автомобильный компрессор шин", "Car tire compressor", 320_000, "tire-compressor"),
        ("Avtomobil tozalovchi shampun", "Автомобильный шампунь", "Car shampoo", 95_000, "car-shampoo"),
        ("Avtomobil mum polirovshchik", "Восковой полироль", "Car polish wax", 145_000, "car-wax"),
        ("Avtomobil suvtushloq toza", "Стеклоомыватель -20", "Windshield washer -20", 28_000, "windshield-fluid"),
        ("Antifriz qizil 5L", "Антифриз красный 5л", "Red antifreeze 5L", 145_000, "antifreeze"),
        ("Tormoz suyuqligi DOT4", "Тормозная жидкость DOT4", "DOT4 brake fluid", 65_000, "brake-fluid"),
        ("Avtomobil zaryadlovchi 12V", "Зарядное устройство 12В", "12V car charger", 240_000, "car-charger"),
        ("Inverter 12V → 220V 1000W", "Инвертор 12В → 220В 1000Вт", "Inverter 12V → 220V 1000W", 580_000, "inverter"),
        ("Bolalar avto-sirtmoqlari", "Детское автокресло", "Child car seat", 1_400_000, "car-seat"),
        ("Avtomobil quv kiriting starter", "Пусковое устройство для авто", "Jump starter", 480_000, "jump-starter"),
    ],

    # ========================================================================
    # HAYVONLAR UCHUN (~25)
    # ========================================================================
    "hayvonlar-uchun": [
        ("It uchun ozuqa 3kg Pedigree", "Корм для собак Pedigree 3кг", "Pedigree dog food 3kg", 145_000, "dog-food"),
        ("It uchun ozuqa 10kg Royal Canin", "Royal Canin корм для собак 10кг", "Royal Canin dog food 10kg", 580_000, "dog-food"),
        ("It uchun ozuqa Pro Plan 7kg", "Pro Plan корм для собак 7кг", "Pro Plan dog food 7kg", 420_000, "dog-food"),
        ("Mushuk uchun ozuqa 2kg Whiskas", "Whiskas корм для кошек 2кг", "Whiskas cat food 2kg", 95_000, "cat-food"),
        ("Mushuk uchun ozuqa Royal Canin 4kg", "Royal Canin корм для кошек 4кг", "Royal Canin cat food 4kg", 320_000, "cat-food"),
        ("Mushuk uchun konserva Whiskas 12", "Whiskas консервы 12 шт", "Whiskas wet food 12 pcs", 95_000, "wet-cat-food"),
        ("Mushuk o'yinchog'i sichqonchasi", "Игрушка-мышка для кошек", "Cat mouse toy", 45_000, "cat-toy"),
        ("Mushuk uchun lazer ko'rsatkichi", "Лазерная указка для кошек", "Laser pointer for cats", 38_000, "cat-laser"),
        ("Mushuk uchun tirnab olish ustuni", "Когтеточка для кошек", "Cat scratching post", 280_000, "scratching-post"),
        ("Mushuk uchun majmua qal'a", "Кошачий комплекс с башней", "Cat tree with tower", 1_200_000, "cat-tree"),
        ("It bo'yinbog'i charm", "Кожаный ошейник для собак", "Leather dog collar", 78_000, "dog-collar"),
        ("It uchun yo'lak", "Поводок для собак", "Dog leash", 95_000, "dog-leash"),
        ("It uchun namozluv kostyumi", "Костюм-дождевик для собак", "Dog raincoat", 220_000, "dog-coat"),
        ("It uchun hojatxona kovrigi", "Пелёнки для собак 50шт", "Dog training pads 50 pcs", 145_000, "dog-pads"),
        ("Mushuk uchun lotok", "Лоток для кошек", "Cat litter box", 180_000, "cat-litter-box"),
        ("Mushuk uchun bentonit qum 10L", "Бентонитовый наполнитель 10л", "Cat litter 10L", 95_000, "cat-litter"),
        ("Akvarium 50L bilan jihoz", "Аквариум 50л с оснащением", "50L aquarium with kit", 850_000, "aquarium"),
        ("Akvarium filtri Aquael", "Фильтр Aquael", "Aquael aquarium filter", 280_000, "aquarium-filter"),
        ("Baliq ozuqasi Tetra", "Корм для рыбок Tetra", "Tetra fish food", 65_000, "fish-food"),
        ("Qush qafasi", "Клетка для попугая", "Bird cage", 480_000, "bird-cage"),
        ("To'tiqush ozuqasi", "Корм для попугая", "Parrot food", 85_000, "parrot-food"),
        ("Quyon uchun ozuqa", "Корм для кроликов", "Rabbit food", 65_000, "rabbit-food"),
        ("Hamster uchun chambar", "Колесо для хомяка", "Hamster wheel", 95_000, "hamster-wheel"),
        ("Hayvonlar uchun shampun", "Шампунь для животных", "Pet shampoo", 78_000, "pet-shampoo"),
        ("Hayvonlar uchun cho'tka", "Щётка для шерсти", "Pet grooming brush", 145_000, "pet-brush"),
    ],
}
