# Generated by Django 5.1.15 on 2026-05-30 05:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='logo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name_uz', models.CharField(max_length=40, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(choices=[('primary', 'Primary (bordoviy)'), ('accent', 'Accent (yashil)'), ('warning', 'Warning (oltin)'), ('sale', 'Sale (qizil)'), ('new', "New (ko'k)"), ('neutral', 'Neutral (kulrang)')], default='primary', max_length=20, verbose_name='color')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image')),
                ('icon', models.CharField(blank=True, default='', help_text="Masalan: 'shopping-bag', 'smartphone'", max_length=60, verbose_name='icon name (lucide-react)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='products count (cached)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit — unique product code', max_length=64, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('short_description', models.CharField(blank=True, default='', max_length=500, verbose_name='short description')),
                ('short_description_uz', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='short description')),
                ('short_description_ru', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='short description')),
                ('short_description_en', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='short description')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='base price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text="Agar chegirma bo'lsa — base_price'dan kichik.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='sale price')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('is_in_stock', models.BooleanField(db_index=True, default=True, verbose_name='in stock')),
                ('ratings_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='ratings avg')),
                ('ratings_count', models.PositiveIntegerField(default=0, verbose_name='ratings count')),
                ('views_count', models.BigIntegerField(default=0, verbose_name='views count')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_new', models.BooleanField(default=False, verbose_name='new arrival')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='bestseller')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='vendors.vendor')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='catalog.producttag')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=80, verbose_name='attribute name')),
                ('name_uz', models.CharField(max_length=80, null=True, verbose_name='attribute name')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='attribute name')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='attribute name')),
                ('value', models.CharField(max_length=200, verbose_name='attribute value')),
                ('value_uz', models.CharField(max_length=200, null=True, verbose_name='attribute value')),
                ('value_ru', models.CharField(max_length=200, null=True, verbose_name='attribute value')),
                ('value_en', models.CharField(max_length=200, null=True, verbose_name='attribute value')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
                'ordering': ('product', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200, verbose_name='alt text')),
                ('alt_text_uz', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='alt text')),
                ('alt_text_ru', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='alt text')),
                ('alt_text_en', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='alt text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ('-is_primary', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='variant SKU')),
                ('color', models.CharField(blank=True, default='', max_length=60, verbose_name='color')),
                ('size', models.CharField(blank=True, default='', max_length=40, verbose_name='size')),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Variant uchun base_price'ga qo'shiladi (yoki ayriladi)", max_digits=10, verbose_name='additional price')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='variant image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ('product', 'color', 'size'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active', 'order'], name='catalog_cat_parent__103bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product', 'order'], name='catalog_pro_product_197719_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='catalog_pro_product_631828_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='product_image_one_primary'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', '-created_at'], name='product_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'is_active'], name='product_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='product_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-ratings_avg'], name='product_rated_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__lte', models.F('base_price')), _connector='OR'), name='product_sale_lte_base'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('ratings_avg__gte', 0), ('ratings_avg__lte', 5)), name='product_ratings_avg_range'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx'),
        ),
    ]
