# Generated by Django 5.1.15 on 2026-05-30 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='code')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=20, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Percentage'da 0..100, fixed'da UZS miqdori", max_digits=12, verbose_name='value')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ('-created_at',),
            },
        ),
    ]
