# Generated by Django 5.1.15 on 2026-05-30 10:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('title_uz', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='title')),
                ('title_ru', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='subtitle')),
                ('subtitle_uz', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='subtitle')),
                ('subtitle_ru', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('link', models.CharField(blank=True, default='', help_text="Internal slug yoki to'liq URL", max_length=500, verbose_name='link')),
                ('position', models.CharField(choices=[('hero', 'Hero (asosiy)'), ('sidebar', 'Sidebar'), ('category', 'Category'), ('footer', 'Footer')], db_index=True, default='hero', max_length=20, verbose_name='position')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ('position', 'order'),
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount applied')),
            ],
            options={
                'verbose_name': 'coupon usage',
                'verbose_name_plural': 'coupon usages',
                'ordering': ('-used_at',),
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Percentage uchun chegirma cap (NULL = chegirma yo'q)", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='max discount (percentage type only)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Buyurtma summasi shu qiymatdan yuqori bo'lishi kerak", max_digits=14, verbose_name='min order amount'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveSmallIntegerField(default=1, help_text='Har user qancha marta ishlatishi mumkin', verbose_name='per-user limit'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='NULL = cheksiz', null=True, verbose_name='global usage limit'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='used count'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid from'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid to'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='coupon_value_non_negative'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['position', 'is_active', 'order'], name='promotions__positio_9384b1_idx'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='promotions__coupon__6ff8ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('coupon', 'user', 'order'), name='coupon_usage_unique_per_order'),
        ),
    ]
