# Generated by Django 6.0.5 on 2026-05-30 04:21

import apps.accounts.managers
import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', help_text='+998XXXXXXXXX formatida', max_length=13, validators=[apps.core.validators.validate_uz_phone], verbose_name='phone')),
                ('full_name', models.CharField(max_length=120, verbose_name='full name')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='preferred language')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20, verbose_name='role')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=10, verbose_name='type')),
                ('recipient_name', models.CharField(max_length=120, verbose_name='recipient name')),
                ('recipient_phone', models.CharField(max_length=13, validators=[apps.core.validators.validate_uz_phone], verbose_name='recipient phone')),
                ('region', models.CharField(max_length=100, verbose_name='region / viloyat')),
                ('city', models.CharField(max_length=100, verbose_name='city / shahar')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='district / tuman')),
                ('street', models.CharField(max_length=200, verbose_name='street')),
                ('building', models.CharField(max_length=30, verbose_name='building')),
                ('apartment', models.CharField(blank=True, default='', max_length=30, verbose_name='apartment')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='postal code')),
                ('landmark', models.CharField(blank=True, default='', max_length=200, verbose_name="landmark / mo'ljal")),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(db_index=True, help_text='Email yoki phone qiymati', max_length=128, verbose_name='target')),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('email_verify', 'Email verification'), ('phone_verify', 'Phone verification'), ('password_reset', 'Password reset'), ('login', 'Login OTP')], max_length=20, verbose_name='purpose')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='max attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'OTP codes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target', 'purpose', '-created_at'], name='accounts_ot_target_cc527e_idx'), models.Index(fields=['expires_at', 'used_at'], name='accounts_ot_expires_44a013_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified', 'is_active'], name='accounts_us_is_emai_d3d27b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='user_unique_phone_when_set'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'type'], name='accounts_ad_user_id_680b07_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'type'), name='address_unique_default_per_type'),
        ),
    ]
